name: ClaudeCodeSwitcher
options:
  bundleIdPrefix: com.claudecode
  deploymentTarget:
    macOS: "26.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"

targets:
  ClaudeCodeSwitcher:
    type: application
    platform: macOS
    sources:
      - path: ClaudeCodeSwitcher
        excludes:
          - "*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claudecode.switcher
        INFOPLIST_FILE: ClaudeCodeSwitcher/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClaudeCodeSwitcher/ClaudeCodeSwitcher.entitlements
        PRODUCT_NAME: "Claude Code Switcher"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
    info:
      path: ClaudeCodeSwitcher/Info.plist
      properties:
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        CFBundleDisplayName: "Claude Code Switcher"
        NSHumanReadableCopyright: "Copyright 2024. All rights reserved."
        LSUIElement: true
